services:
  db:
    image: postgres:16.1
    container_name: shareit
    ports:
      - "5438:5432"
    volumes:
      - ./volumes/shareit:/var/lib/shareit/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 20s
      interval: 20s
      retries: 10